- Front_end/car-reviews/package.json
- Front_end/car-reviews/src/App.js
- Front_end/car-reviews/src/Components/Featured_reviews.js
- Front_end/car-reviews/src/Components/Navigation.js
- Front_end/car-reviews/src/Components/Search.js
- Front_end/car-reviews/src/Components/Stars.js
- Front_end/car-reviews/yarn.lock
> Dgm client star rating

- Front_end/car-reviews/src/App.js
- Front_end/car-reviews/src/Components/Navigation.js
Initial Top Navigation and Side Navigation
> Initial top navbar and side nav

- Front_end/car-reviews/src/App.js
- Front_end/car-reviews/src/Components/Navigation.js
- Front_end/car-reviews/src/Components/Search.js
For now just representational select search component with no functionality.
> Dgm client landing page search

- Front_end/car-reviews/package.json
- Front_end/car-reviews/src/App.js
- Front_end/car-reviews/src/Components/reviewlist.js
- Front_end/car-reviews/src/index.js
- Front_end/car-reviews/yarn.lock
> Started layout of review list component

- Front_end/package.json
- Front_end/src/App.js
- Front_end/src/Components/Landing_page.js
- Front_end/src/Components/Search.js
- Front_end/src/index.js
- Front_end/yarn.lock
Styling fixes, Materialize was clashing with Bootstrap. Added landing_page.js and routing.
> Dgm client styling fixes

- Back_end/server.js
- [] Incomplete/work-in-progress, PR is for discussion/feedback
- [] Test A
- [] Test B
- [] My code has been reviewed by at least one peer
- [] I have commented my code, particularly in hard to understand areas
> Ft client billing

- Back_end/package.json
- [] Incomplete/work-in-progress, PR is for discussion/feedback
- [] Test A
- [] Test B
- [] My code has been reviewed by at least one peer
- [] I have commented my code, particularly in hard to understand areas
> forgot to change index.js to server.js in package.json. bug fixed.

- Front_end/src/Components/LogInModal.js
- Front_end/src/Components/Navigation.js
- Front_end/src/Components/SignUpModal.js
- [] Bug fix (non-breaking change witch fixes an issue)
- [] Complete, but not tested (may need new tests)
- [] Incomplete/work-in-progress, PR is for discussion/feedback
- [] Test B
- [] My code has been reviewed by at least one peer
- [] There are no merge conflicts
> Willkwon client lpmodal

- Front_end/src/Components/FeaturedReviews.js
> Updated import file name camelCase bug fix

- Front_end/src/App.js
- Front_end/src/Components/Billing.js
Billing page completed. Resembles closely to wireframe.
- [] Bug fix (non-breaking change witch fixes an issue)
- [] Incomplete/work-in-progress, PR is for discussion/feedback
- [] Test A
- [] Test B
- [] My code has been reviewed by at least one peer
- [] I have commented my code, particularly in hard to understand areas
> Billing page completed. Resembles closely to wireframe.

- Front_end/src/Components/FeaturedReviewCard.js
- Front_end/src/Components/ReviewCardPop.js
Featured review modal goes to review
> Dgm client review modal

- Back_end/routes/reviewRoutes.js
- Back_end/server.js
Reverts Lambda-School-Labs/labs9-car-reviews#36 attempting to fix frontend deployment
> Revert "added sanity check at the root"

- Front_end/src/Components/SearchLanding/SearchLanding.js
> More import changes due to folders/components restructure.

- Front_end/src/Components/Billing/Billing.js
- Front_end/src/Components/ReviewList/ReviewList.js
More and more fixes on import names
> More and more imports change.

- Front_end/src/Components/Navigation/Navigation.js
- Front_end/yarn.lock
Used wrong directory to import card modals. Should be fixed.
> Forgot to commit changes to Navigation.js

- Front_end/src/Components/Firebase/firebase.js
- Front_end/src/Components/Login/LogInForm.js
- Front_end/src/Components/Login/LogInWithGoogle.js
- Front_end/src/Components/Signup/SignUpForm.js
Added social authentication
Change Status
> Wk firebase

- Front_end/src/App.css
- Front_end/src/App.js
- Front_end/src/Components/Firebase/firebase.js
- Front_end/src/Components/ForgotPassword/ForgotPasswordForm.js
- Front_end/src/Components/ForgotPassword/ForgotPasswordPage.js
- Front_end/src/Components/Login/LogInForm.js
Added reset password functionality
> added reset password functionality

- Front_end/src/Components/Navigation/Breadcrumbs.js
- Front_end/src/Components/Navigation/Navigation.js
Functional breadcrumbs component.
> Dgm client breadcrumbs

- Back_end/index.js
- Front_end/src/Components/Navigation/Navigation.js
- Front_end/src/Components/ReviewList/ReviewList.js
Updated nav bar menu links and commented out the back en user_routes because of a bug.
- [] Complete, but not tested (may need new tests)
- [] Test A
- [] Test B
- [] My changes generate no new warnings
- [] There are no merge conflicts
> hooked up links in nav bar and commented out userroutes in index.js

- Front_end/src/Components/Billing/Billing.js
- Front_end/src/Components/ReviewList/ReviewList.js
- Front_end/src/Components/Settings/SettingsPage.js
updated nav links, cleaned up billing page, and added navbar to the settings page
- [] Complete, but not tested (may need new tests)
- [] Test A
- [] Test B
- [] My changes generate no new warnings
- [] There are no merge conflicts
> updated nav links, cleaned up billing page, and added navbar to settings page

- Front_end/public/DummyData/dummyData.json
- Front_end/src/Components/Display/FeaturedReviewCard.js
- Front_end/src/Components/Display/FeaturedReviews.js
- Front_end/src/Components/Display/PopularCars.js
- Front_end/src/Components/Display/PopularTracksCard.js
- Front_end/src/Components/Navigation/Navigation.js
Displaying dummy data pulled from Spotify API
> Dummy data population

- Front_end/src/Components/Login/LogInWithGoogle.js
- Front_end/src/Components/Settings/SettingsContent.js
- Front_end/src/Components/Signup/SignUpForm.js
Made it so that user can migrate to heroku.  Settingspage and signupform and loginwithgoogle components are now able to post and get data from the heroku database.
> connected firebase to heroku

- Front_end/src/Components/ReviewList/ReviewList.js
added mapping for review cards on user review page using heroku endpoint)
- [] Complete, but not tested (may need new tests)
- [] Test A
- [] Test B
- [] My changes generate no new warnings
- [] There are no merge conflicts
> added mapping for review cards on user review page using heroku endpoint

- Front_end/src/Components/Navigation/Navigation.js
> Dgm fixed menu links

- Back_end/index.js
Uncommented user routes references. Endpoints should work correctly now.
> Uncommented user routes references in index.js.

- Front_end/src/Components/Display/FeaturedReviews.js
> Back end pull to front end

- Front_end/src/Components/SearchLanding/SearchView.js
> Connected the user table and reading from it.

- Front_end/src/Components/Login/LogInWithGoogle.js
- Front_end/src/Components/Navigation/Breadcrumbs.js
- Front_end/src/Components/SplashPage/SplashPage.js
changed route after login and text change on splash
> changed route after login and text change on splash

- Back_end/constants/frontEnd.js
- Back_end/index.js
- Back_end/server.js
- Front_end/src/Components/ReviewsPage/ReviewsPage.js
Modified code to retrieve token from server. Will have to reconfigure other files if it works.
Tested on localhost/heroku. Seemed to be working at the moment.
> Testing token retrieval in production environment

- Back_end/index.js
Changed CORS options for now. Need to get backend to work.
> Removed CORS options as it broke the deployed site.

- Back_end/routes/albumReviewRoutes.js
- Back_end/routes/trackReviewRoutes.js
ReviewText should have been changed to Review.
> Revised post/put endpoints for both album/track reviews. 

- Back_end/index.js
- Front_end/src/App.js
Trying another configuration 
Tested on localhost in both normal and incognito windows.
> Changed front and back end configuration to test token retrieval.

- Front_end/src/Components/CardModals/ReviewCreateModal.js
- Front_end/src/Components/CardModals/ReviewEditModal.js
- Front_end/src/Components/ReviewList/ProfileReviewCard.js
- Front_end/src/Components/ReviewList/ReviewList.js
added metadata retrieval to edit review list
> added spotify metadata retrieval for edit reviews.

- Front_end/src/Components/ArtistPage/AlbumCard.js
- Front_end/src/Components/ArtistPage/ArtistPage.js
- Front_end/src/Components/Search/Search.js
fixed layout issues with new artist page.
> fixed some layout issues with artist page.

- Front_end/src/App.js
- Front_end/src/Components/ReviewList/UserReviewList.js
changed name and route name of ReviewList to UserReviewList
> changed name and route name of ReviewList to UserReviewList

- Front_end/src/Components/Signup/SignUpForm.js
added confirmation password field and matching check to signup
> added confirmation password field and matching check to signup

- Back_end/data/usersDb.js
- Back_end/routes/spotifyRoutes.js
- Back_end/routes/userRoutes.js
- Front_end/src/App.js
- Front_end/src/Components/Billing/Billing.js
- Front_end/src/Components/Billing/Checkout.js
- Front_end/src/Components/Navigation/Navigation.js
- Front_end/src/Components/Signout/SignOut.js
- Front_end/src/index.js
Made billing dynamic (monthly/yearly subscription). Added code in App.js to store user information for other components to use.
> Moved User's information to App.js. Dynamic billing

- Front_end/src/Components/ReviewsPage/AlbumReviewsPage.js
- Front_end/src/Components/ReviewsPage/TrackReviewsPage.js
Adding Links to tracks, albums, and artists for UX.
Tested on localhost.
> Adding Links to tracks, albums, and artists.

- Front_end/src/App.js
- Front_end/src/Components/CardModals/AlbumReviewCreateModal.js
- Front_end/src/Components/CardModals/TrackReviewCreateModal.js
- Front_end/src/Components/Navigation/Navigation.js
- Front_end/src/Components/ReviewList/ProfileReviewCard.js
- Front_end/src/Components/ReviewList/UserReviewList.js
- Front_end/src/Components/ReviewsPage/AlbumReviewsPage.js
- Front_end/src/Components/ReviewsPage/TrackReviewsPage.js
Working on getting dynamic routing for user review page
> Al client user reviews

- Back_end/.gitignore
- Front_end/src/App.js
- Front_end/src/Components/Login/LogInWithGoogle.js
- Front_end/src/Components/Settings/SettingsContent.js
- Front_end/src/Components/Signup/SignUpForm.js
- Front_end/src/Components/Signup/SignUpPage.js
Fixed some bugs related to login/sign up/sign out. Changed related backend routes from /user to /users
Tested on localhost
> Fixed log in state. Fixed Users endpoint to backend

- Front_end/src/Components/Navigation/Navigation.js
- Front_end/src/Components/Navigation/PlansModal.js
Reverts Lambda-School-Labs/labs9-music-reviews#160
> Revert "Adf nav responsive"

- Front_end/src/Components/ReviewsPage/AlbumReviewsPage.js
- Front_end/src/Components/ReviewsPage/TrackReviewsPage.js
Reviewers can only give one review for an album or a track
> Can only give review once

- Back_end/routes/userRoutes.js
- Front_end/src/Components/Billing/Billing.js
- Front_end/src/Components/Billing/Checkout.js
- Front_end/src/Components/HomePage.js
- Front_end/src/Components/LandingPage/LandingPage.js
- Front_end/src/Components/Navigation/Navigation.js
- Front_end/src/Components/Navigation/PlansModal.js
- Front_end/src/Components/ReviewsPage/AlbumReviewsPage.js
- Front_end/src/Components/ReviewsPage/TrackReviewsPage.js
- Front_end/src/Components/Settings/SettingsContent.js
Responsive design on navbar. Fixed previous malfunctioning change nickname function.
> Debugged nickname route to change nickname. Navbar responsive design.

- Front_end/src/Components/CardModals/AlbumReviewCreateModal.js
Commented out disc dropdown in create review modal for demo
> Commented out disc dropdown in create review modal for demo

- Front_end/src/App.css
- Front_end/src/App.js
- Front_end/src/Components/Billing/Billing.js
- Front_end/src/Components/Display/NewReleaseCard.js
- Front_end/src/Components/Display/Newest.js
- Front_end/src/Components/Display/PopularTracks.js
- Front_end/src/Components/LandingPage/LandingPage.css
- Front_end/src/Components/LandingPage/LandingPage.js
- Front_end/src/Components/Login/LogInForm.js
- Front_end/src/Components/Login/LogInPage.js
- Front_end/src/Components/Login/LogInWithGoogle.js
- Front_end/src/Components/Login/Login.css
- Front_end/src/Components/Navigation/Navigation.css
- Front_end/src/Components/Navigation/Navigation.js
- Front_end/src/Components/Navigation/PlansModal.js
- Front_end/src/Components/Search/Search.css
- Front_end/src/Components/Search/Search.js
- Front_end/src/Components/Search/SearchResults.js
- Front_end/src/Components/Settings/SettingsContent.js
- Front_end/src/index.css
> Styling/layout/design changes.

- Front_end/src/Components/Login/LogInForm.js
- Front_end/src/Components/Login/LogInWithGoogle.js
- Front_end/src/Components/Login/Login.css
> Login page styling

- Front_end/src/Components/Login/LogInForm.js
- Front_end/src/Components/Login/LogInWithGoogle.js
- Front_end/src/Components/Login/Login.css
- Front_end/src/Components/Signup/SignUpForm.js
- Front_end/src/Components/Signup/SignUpPage.js
- Front_end/src/Components/Signup/Signup.css
Signup page styling. Other issues fixed.
> Signup page style. Fixed some other issues.

- Back_end/data/usersDb.js
> error fixing

- Back_end/data/usersDb.js
- Front_end/src/Components/Navigation/Navigation.js
- Front_end/src/Components/Navigation/PlansModal.js
- Front_end/src/Components/Settings/SettingsContent.js
previous merge was showing time in epoch time.
> Hot fix for subscription date. 

- Back_end/data/usersDb.js
- Front_end/src/Components/Navigation/Navigation.js
- Front_end/src/Components/Navigation/PlansModal.js
- Front_end/src/Components/Settings/SettingsContent.js
Reverts Lambda-School-Labs/labs9-music-reviews#199
> Revert "Hot fix for subscription date. "

- Front_end/src/Components/Display/NewReleaseCard.js
- Front_end/src/Components/Display/Newest.js
- Front_end/src/Components/Display/PopularTracks.js
- Front_end/src/Components/HomePage.js
> Styling home page

- Front_end/src/Components/CardModals/AlbumReviewCreateModal.js
- Front_end/src/Components/CardModals/TrackReviewCreateModal.js
- Front_end/src/Components/ReviewList/AlbumProfileReviewCard.js
- Front_end/src/Components/ReviewList/TrackProfileReviewCard.js
- Front_end/src/Components/ReviewList/UserReviewList.js
- Front_end/src/Components/StarsRating/ViewStars.js
updated user review list styling and create new review modals stylings
> updated user review list styling and create new review modals stylings

- Front_end/public/index.html
- Front_end/src/Components/ReviewsPage/reviews.css
> Styled scroll bar

- Front_end/src/App.css
- Front_end/src/App.js
- Front_end/src/Components/CardModals/AlbumReviewCreateModal.js
- Front_end/src/Components/CardModals/ReviewEditModal.js
- Front_end/src/Components/CardModals/TrackReviewCreateModal.js
- Front_end/src/Components/CardModals/TrackReviewEditModal.js
- Front_end/src/Components/Display/NewReleaseCard.js
- Front_end/src/Components/Display/Newest.js
- Front_end/src/Components/Display/PopularTracks.js
- Front_end/src/Components/HomePage.js
- Front_end/src/Components/LandingPage/LandingPage.js
- Front_end/src/Components/Search/Search.js
- Front_end/src/Components/Settings/SettingsContent.js
- Front_end/src/index.css
- Front_end/src/index.js
Styling change on multiple pages. Most significant change would be the background image. Now set to body instead of Container in App.js. Also change date being used so it'll only return year, month, and day. 
Tested locally.
> Styling Changes

- Front_end/package.json
- Front_end/public/index.html
- Front_end/src/App.js
- Front_end/src/Components/HomePage.js
- Front_end/src/Components/Login/LogInForm.js
- Front_end/src/Components/Login/LogInWithGoogle.js
- Front_end/src/Components/Navigation/Navigation.css
- Front_end/src/Components/Navigation/Navigation.js
- Front_end/src/Components/Signout/SignOut.js
- Front_end/src/Components/Signup/SignUpForm.js
- Front_end/yarn.lock
- yarn-error.log
> Adf menu dropdown menu

- Front_end/src/Components/CardModals/AlbumReviewCreateModal.js
- Front_end/src/Components/CardModals/ReviewEditModal.js
- Front_end/src/Components/CardModals/TrackReviewCreateModal.js
- Front_end/src/Components/CardModals/TrackReviewEditModal.js
- Front_end/src/Components/ReviewList/UserReviewList.js
- Front_end/src/Components/StarsRating/EditStars.js
updated styling for all review based modals
> updated styling for all review based modals

- Front_end/src/App.js
- Front_end/src/Components/Settings/SettingsContent.js
- Front_end/src/Components/Settings/SettingsPage.js
Previously the expiration date was using state as a reference. It has been changed to props.
> Billing should be debugged

- Front_end/src/Components/Navigation/Navigation.css
- Front_end/src/Components/Navigation/Navigation.js
- Front_end/src/Components/Signout/SignOut.js
> dropdown styling
